CitasMecanica/CitasMecanica/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views as core
from usuario import views as usuario
from django.conf import settings
from vehiculo import views as vehiculo
from mecanico import views as mecanico
from cita import views as cita
from django.contrib.auth import views as auth_views #import this

urlpatterns = [
    path('', core.home, name="home"),
    path('admin/', admin.site.urls), 
    path('login/', usuario.autent, name='SignIn'),
    path('registro/', usuario.registrar, name='SignUp'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('perfil/modificar/',usuario.profileupdate,name='profileUpdate'),
    path('perfil/',usuario.renderprofile,name='profileUser'),
    path('restablecer-contraseña/', auth_views.PasswordResetView.as_view(template_name="autenticacion/password-reset.html"), name='password_reset'),
    path('restablecer-contraseña-enviado/', auth_views.PasswordResetDoneView.as_view(template_name="autenticacion/password_reset_done.html"), name='password_reset_done'),
    path('restablecer/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="autenticacion/password-confirm.html"), name='password_reset_confirm'),
    path('restablecer-contraseña-completa/', auth_views.PasswordResetCompleteView.as_view(template_name="autenticacion/password_reset_complete.html"), name='password_reset_complete'),

    #------------------------------------------------------------------------
    
    path('vehiculo/',vehiculo.rendervehiculo,name='vehiculo'),
    path('vehiculo/modificar/',vehiculo.vehiculoupdate,name='vehiculoupdate'),
    path('vehiculo/añadir/',vehiculo.vehiculoadd,name='vehiculoAdd'),
    path('vehiculo/eliminar/<id>/',vehiculo.deletevehiculo,name='deletevehiculo'),

    #------------------------------------------------------------------------
    
    path('mecanicos/',mecanico.mecanicos,name='mecanicos'),

    #------------------------------------------------------------------------
    
    path('citas/',cita.renderCita,name='cita'),
    path('citas/añadir',cita.citaAdd,name='citaAdd'),
    path('citas/modificar/<id>/',cita.citaUpdate,name='citaUpdate'),
    path('citas/eliminar/<id>/',cita.citaDelete,name='vehiculoDelete'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CitasMecanica/vehiculo/models.py
from django.db import models
from usuario.models import Profile

# Create your models here.
class Vehiculo(models.Model):
    duenio = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    placa=models.CharField(max_length=30, blank=True, null=True,verbose_name="placa" )
    marca=models.CharField(max_length=30, blank=True, null=True,verbose_name="marca" )
    modelo=models.CharField(max_length=30, blank=True, null=True,verbose_name="modelo" )
    anovehiculo=models.DateField(blank=True, null=True,verbose_name="año del vehiculo" )
    
    def __str__(self):
        return f"{self.placa}"

    class Meta:
        verbose_name = 'vehiculo'
        verbose_name_plural = 'vehiculos'

CitasMecanica/vehiculo/forms.py
from django import forms
from .models import Vehiculo

class vehiculoforms(forms.ModelForm):
    placa=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "placa",
                'placeholder' : " "
            }
        )
    )
    marca=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "marca",
                'placeholder' : " "
            }
        )
    )
    modelo=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "modelo",
                'placeholder' : " "
            }
        )
    )

    anovehiculo=forms.DateField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "date",
                'id' : "anovehiculo",
                'placeholder' : " "
            }
        )
    )
    
    class Meta:
        model=Vehiculo
        fields=['duenio','placa','marca','modelo','anovehiculo']

class vehiculoupdateform(forms.ModelForm):
    placa=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "placaedit",
                'placeholder' : ""
            }
        )
    )
    marca=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "marcaedit",
                'placeholder' : ""
            }
        )
    )
    modelo=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "modeloedit",
                'placeholder' : ""
            }
        )
    )

    anovehiculo=forms.DateField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "date",
                'id' : "anovehiculoedit",
                'placeholder' : ""
            }
        )
    )
    class Meta:
        model=Vehiculo
        fields=['placa','marca','modelo','anovehiculo']

CitasMecanica/vehiculo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Vehiculo
from .forms import vehiculoforms, vehiculoupdateform
from django.contrib.auth.models import User

# Create your views here.
def rendervehiculo(request):
    usuario= get_object_or_404(User, pk=request.user.id)
    role = []
    if usuario.groups.filter(name='Clientes').exists():
        role = "Cliente"
    else:
        role = "Mecánico"
    vehiculos=Vehiculo.objects.filter(duenio=request.user.id)
    vehiculoUpdate = vehiculoupdateform()
    
    data={
        "vehiculos":vehiculos,
        "vehiculoUpdate": vehiculoUpdate,
        'role':role
    }
    return render(request, "vehiculo/vehiculo.html",data)

def vehiculoupdate(request):
    product = Vehiculo.objects.get(pk=request.POST.get("idVehiculo"))
    formulario = vehiculoupdateform(
        request.POST, instance=product
    )
    if formulario.is_valid:
        formulario.save()
        return redirect(to="vehiculo")


def vehiculoadd(request):
    data={
        'vehiculoadd':vehiculoforms()
    }
    if request.method=='POST':
        formulario=vehiculoforms(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect(to='vehiculo')
        else: 
            data["vehiculoadd"]=formulario
    return render(request, "vehiculo/vehiculoAdd.html",data)

def deletevehiculo(request,id):
    vehiculos=get_object_or_404(Vehiculo,id=id)
    vehiculos.delete()
    return redirect(to="vehiculo")

CitasMecanica/vehiculo/templates/vehiculo/vehiculo.html
{% extends 'core/base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<div class="container-xxl">
    <h1>Vehiculos Ingresados</h1>
    <div class="contenedorSobreponer">
        <div class="sobrePoner">
            {% if perms.vehiculo.add_vehiculo %}
            <a class="btn btn-primary botonAceptar" href="{% url 'vehiculoAdd' %}" role="button"><i class="bi bi-car-front-fill"></i> Añadir</a>
            {% endif %}
        </div>
    </div>
    <div class="row gx-4 row-cols-md-3 row-cols-xl-4">
        {% for vehiculo in vehiculos %}
            <div class="col ms-md-4">
                <div class="card" style="width: 18rem;">
                    <div class="card-header">
                        {{vehiculo.placa}}
                    </div>
                    <div class="card-body">
                        <h5 class="card-title mb-1">{{vehiculo.marca}}</h5>
                        <p class="card-text mt-2">{{vehiculo.modelo}} <br>
                        {{vehiculo.anovehiculo}}</p>
                        <div class="d-grid gap-2 d-flex justify-content-center ">
                            <a type="button" onclick="editvehiculo( '{{vehiculo.id}}', '{{vehiculo.placa}}', '{{vehiculo.marca}}', '{{vehiculo.modelo}}', `{{vehiculo.anovehiculo|date:'Y/m/d'}}`)" class="btn btn-primary botonAceptar btn-sm m-md-2" data-bs-toggle="modal" data-bs-target="#staticBackdrop"><i class="bi bi-pencil-square"></i></a>
                            <a type="button" onclick="deletevehiculo('{{vehiculo.id}} ')" class="btn btn-danger btn-sm m-md-2 botonEliminar"><i class="bi bi-trash3"></i></a>
                          </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block modales %}{% include "vehiculo/vehiculoUpdate.html" %}{% endblock modales %}

{% block js %}
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    function editvehiculo(id, placa,marca, modelo, anovehiculo){
        var date = new Date(anovehiculo),
    mnth = ("0" + (date.getMonth() + 1)).slice(-2),
    day = ("0" + date.getDate()).slice(-2);
            document.getElementById('idVehiculo').value = id;
            document.getElementById('placaedit').value = placa;
            document.getElementById('marcaedit').value = marca;
            document.getElementById('modeloedit').value = modelo;
            document.getElementById("anovehiculoedit").value=[date.getFullYear(), mnth, day].join("-");
    console.log(date)
  console.log([date.getFullYear(), mnth, day].join("-"));
    }
     
    function deletevehiculo(id) {
        Swal.fire({
            "title": `¿Desea Eliminar Vehiculo?`,
            "icon": "question",
            'text':``,
            "showCancelButton": true,
            "cancelButtonText": "Cancelar",
            "confirmButtonText": "Eliminar",
            "reverseButtons": true,
            "cancelButtonColor": "#934d85",
            "confirmButtonColor": "#FE33E5"
        })
        .then(function(result){
            if(result.isConfirmed){
                window.location.href = "/vehiculo/eliminar/"+id+"/"
            }
        })
    }

</script>
{% endblock js %}

CitasMecanica/vehiculo/templates/vehiculo/vehiculoAdd.html
{% extends 'core/base.html' %}

{% block title %}Inicio{% endblock %}

{% block content %}
<div class="container p-3">
<h1>Agregar Vehiculos</h1>
<form method='post'>
    {% csrf_token %}
    <input class="hidden" type="hidden" name="duenio" id="id_duenio" value="{{ user.id }}">
    <div class='mb-3'>
    <label>Placa: </label>
    {{vehiculoadd.placa}}
    </div>
    <div class='mb-3'>
    <label>Marca:</label>
    {{vehiculoadd.marca}}
    </div>
    <div class='mb-3'>
    <label>Modelo:</label>
    {{vehiculoadd.modelo}}
    </div>
    <div class='mb-3'>
    <label>Año del Vehiculo</label>
    {{vehiculoadd.anovehiculo}}
    </div>
    <a class="btn btn-secondary" href="{% url 'vehiculo' %}" role="button">Cancelar</a>
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
</div>
{% endblock %}

CitasMecanica/vehiculo/templates/vehiculo/vehiculoUpdate.html
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Modificar Vehiculo</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'vehiculoupdate' %}" method="post">
            {% csrf_token %}
            <input type="hidden" id="idVehiculo" name="idVehiculo">
            <div class='mb-3'>
              <label>Placa</label>
              {{ vehiculoUpdate.placa }}
              </div>
              <div class='mb-3'>
              <label>Marca</label>
              {{ vehiculoUpdate.marca }}
              </div>
              <div class='mb-3'>
              <label>Modelo</label>
              {{ vehiculoUpdate.modelo }}
              </div>
              <div class='mb-3'>
              <label>Año del Vehiculo</label>
              {{ vehiculoUpdate.anovehiculo }}
              </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
        </form>
      </div>
    </div>
  </div>