CitasMecanica/CitasMecanica/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views as core
from usuario import views as usuario
from django.conf import settings
from vehiculo import views as vehiculo
from mecanico import views as mecanico
from cita import views as cita
from django.contrib.auth import views as auth_views #import this

urlpatterns = [
    path('', core.home, name="home"),
    path('admin/', admin.site.urls), 
    path('login/', usuario.autent, name='SignIn'),
    path('registro/', usuario.registrar, name='SignUp'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('perfil/modificar/',usuario.profileupdate,name='profileUpdate'),
    path('perfil/',usuario.renderprofile,name='profileUser'),
    path('restablecer-contraseña/', auth_views.PasswordResetView.as_view(template_name="autenticacion/password-reset.html"), name='password_reset'),
    path('restablecer-contraseña-enviado/', auth_views.PasswordResetDoneView.as_view(template_name="autenticacion/password_reset_done.html"), name='password_reset_done'),
    path('restablecer/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="autenticacion/password-confirm.html"), name='password_reset_confirm'),
    path('restablecer-contraseña-completa/', auth_views.PasswordResetCompleteView.as_view(template_name="autenticacion/password_reset_complete.html"), name='password_reset_complete'),

    #------------------------------------------------------------------------
    
    path('vehiculo/',vehiculo.rendervehiculo,name='vehiculo'),
    path('vehiculo/modificar/',vehiculo.vehiculoupdate,name='vehiculoupdate'),
    path('vehiculo/añadir/',vehiculo.vehiculoadd,name='vehiculoAdd'),
    path('vehiculo/eliminar/<id>/',vehiculo.deletevehiculo,name='deletevehiculo'),

    #------------------------------------------------------------------------
    
    path('mecanicos/',mecanico.mecanicos,name='mecanicos'),

    #------------------------------------------------------------------------
    
    path('citas/',cita.renderCita,name='cita'),
    path('citas/añadir',cita.citaAdd,name='citaAdd'),
    path('citas/modificar/<id>/',cita.citaUpdate,name='citaUpdate'),
    path('citas/eliminar/<id>/',cita.citaDelete,name='vehiculoDelete'),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

CitasMecanica/usuario/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    direccion=models.CharField(max_length=150,blank=True,null=True,verbose_name="direccion")
    telefono=models.CharField(max_length=10,blank=True,null=True,verbose_name="telefono")
    ocupacion=models.CharField(max_length=30,blank=True,null=True,verbose_name="ocupacion")
    fechanacimiento=models.DateField(blank=True,null=True,verbose_name="fecha de nacimiento")
    def __str__(self):
        return f"{self.user.username} | {self.user.first_name}"

    class Meta:
        verbose_name = 'perfil'
        verbose_name_plural = 'perfiles'

CitasMecanica/usuario/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Profile
from mecanico.models import Mecanico

class UserCreationForm(UserCreationForm):
    username=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "username",
                'placeholder' : "Nombre Usuario"
            }
        )
    )
    first_name=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "first_name",
                'placeholder' : "Primer Nombre"
            }
        )
    )
    last_name=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "last_name",
                'placeholder' : "Apellido"
            }
        )
    )
    email=forms.EmailField(
         widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "email",
                'id' : "email",
                'placeholder' : "Correo Electronico"
            }
        )
    )
    password1=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "password",
                'id' : "password1",
                'placeholder' : "Contraseña"
            }
        )
    )
    password2=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "password",
                'id' : "password2",
                'placeholder' : "Verificar Contraseña"
            }
        )
    )
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]
class AuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "username",
                'placeholder' : "Nombre Usuario"
            }
        )
    )

    password = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "password",
                'id' : "password",
                'placeholder' : "Contraseña"
            }
        )
    )
class profileform(forms.ModelForm):
    ocupacion=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "ocupacion",
                'placeholder' : "Ocupación"
            }
        )
    )
    telefono=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "telefono",
                'placeholder' : "Teléfono"
            }
        )
    )
    direccion=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "direccion",
                'placeholder' : "Dirección"
            }
        )
    )
    fechanacimiento=forms.DateField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "date",
                'id' : "fechanacimiento",
                'placeholder' : "Fecha de Nacimiento"
            }
        )
    )


    class Meta:
        model=Profile 
        exclude=['user']
        fields=['direccion','ocupacion','fechanacimiento','telefono']

class userupdate(forms.ModelForm):
    first_name=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "first_name",
                'placeholder' : "Primer Nombre"
            }
        )
    )
    last_name=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "last_name",
                'placeholder' : "Apellido"
            }
        )
    )
    class Meta:
        model=User
        fields=['first_name','last_name']

class mecanicoform(forms.ModelForm):
    cargo=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "cargo",
                'placeholder' : "Cargo"
            }
        )
    )
    telefono=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "telefono",
                'placeholder' : "Teléfono"
            }
        )
    )
    direccion=forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "text",
                'id' : "direccion",
                'placeholder' : "Dirección"
            }
        )
    )
    fechanacimiento=forms.DateField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'type' : "date",
                'id' : "fechanacimiento",
                'placeholder' : "Fecha de Nacimiento"
            }
        )
    )

    imagen = forms.ImageField(
        widget=forms.FileInput(
        attrs={
                'class': 'form-control',
                'type':'file',
                'id' : "imagen",
                'placeholder' : "Foto de Perfil"
        })
    )
    class Meta:
        model=Mecanico 
        exclude=['user']
        fields=['imagen','direccion','cargo','fechanacimiento','telefono']

CitasMecanica/usuario/views.py
from django.shortcuts import redirect, render,get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from .forms import UserCreationForm, AuthenticationForm, profileform, userupdate, mecanicoform
from django.contrib import auth
from django.contrib import messages
from.models import Profile
from mecanico.models import Mecanico
from django.contrib.auth.models import User, Group
# Create your views here.

def autent(request):
    data = {
        'form': AuthenticationForm()
    }
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = auth.authenticate(username = form.cleaned_data["username"], password =form.cleaned_data["password"])
            auth.login(request, user)
            return redirect(to="home") 
        data["form"] = form

    return render(request, 'autenticacion/SignIn.html', data)

def registrar(request):
    data = {
        'form': UserCreationForm()
    }
    
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name='Clientes')
            user.groups.add(group)
            user = auth.authenticate(username = form.cleaned_data["username"], password =form.cleaned_data["password1"])
            auth.login(request, user)
            messages.success(request, "Te has registrado con exito")
            return redirect(to="home") 
        data["form"] = form
    return render(request, "autenticacion/SignUp.html", data)

def profileupdate(request):
    usuario= get_object_or_404(User, pk=request.user.id)
    perfil= []
    data = {}
    if usuario.groups.filter(name='Clientes').exists():
        perfil = get_object_or_404(Profile, user=usuario.id)
        data = {
            "userform":userupdate(instance=usuario),
            'profile': profileform(instance=perfil),
            'role': 'Cliente'
        }
        if request.method == 'POST':
            formulario2 = userupdate(data=request.POST,instance=usuario)
            formulario = profileform(data=request.POST, instance=perfil)
            if formulario.is_valid() and formulario2.is_valid():
                formulario.save()
                formulario2.save()
                messages.success(request, f'El Perfil se modificó con exito')
                return redirect(to="profileUser")
            else:
                data["profile"] = formulario
                data["userform"]= formulario2
    else:
        perfil = get_object_or_404(Mecanico, user=usuario.id)
        data = {
            "userform":userupdate(instance=usuario),
            'profile': mecanicoform(instance=perfil),
            'role': 'Mecánico'
        }
        if request.method == 'POST':
            formulario2 = userupdate(request.POST,instance=usuario)
            formulario = []
            if usuario.groups.filter(name='Clientes').exists():
                formulario = profileform(data=request.POST, instance=perfil)
            else:
                formulario = mecanicoform(request.POST, request.FILES, instance=perfil)
            if formulario.is_valid() and formulario2.is_valid():
                print('Si')
                formulario.save()
                formulario2.save()
                return redirect(to="profileUser")
            else:
                print('Error')
                data["profile"] = formulario
                data["userform"]= formulario2
    return render(request, 'usuario/ProfileUpdate.html', data)

def renderprofile(request):
    usuario= get_object_or_404(User, pk=request.user.id)
    perfil= []
    role = []
    if usuario.groups.filter(name='Clientes').exists():
        perfil = get_object_or_404(Profile, user=usuario.id)
        role = "Cliente"
    else:
        perfil = get_object_or_404(Mecanico, user=usuario.id)
        role = "Mecánico"
    data={'profile':perfil,'user':usuario, 'role': role}
    return render(request,'usuario/Profile.html',data)

CitasMecanica/usuario/templates/autenticacion/SignUp.html
{% extends 'autenticacion/base.html' %} 

{% block title %}Registro{% endblock title %} 

{% block form %}
<div class="col bg-white p-5 rounded-end">
  <h2 class="fw-bold text-center pb-4">Registro</h2>
  {% if form.errors %}
                {% for field in form %}
                {% if field.errors %}
                {% for error in field.errors %}
                <script>
                    $.alert({
                        title: '',
                        theme:'material',
                        type: 'red',
                        content: '{{ error | escape }}'
                    });
                </script>
                {% endfor %}
                {% endif %}
                {% endfor %}


                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <script>
                        $.alert({
                            title: '¡Importante!',
                            theme:'material',
                            type: 'red',
                            content: '{{ error | escape }}'
                        });
                </script>
                {% endfor %}
                {% endif %}
            {% endif %}
  <!-- Registro -->
  <form action="#" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-sm mb-4">
        <label for="text" class="form-label font_color">Nombre:</label>
        {{form.first_name}}
      </div>
      <div class="col-sm mb-4">
        <label for="text" class="form-label font_color">Apellido:</label>
        {{form.last_name}}
      </div>
    </div>
    <div class="mb-4">
      <label for="username" class="form-label font_color">Usuario:</label>
      {{form.username}}
    </div>
    <div class="mb-4">
      <label for="email" class="form-label font_color"
        >Correo Electrónico:</label
      >
      {{form.email}}
    </div>
    <div class="row">
      <div class="col-sm mb-4">
        <label for="password" class="form-label font_color">Contraseña:</label>
        {{form.password1}}
      </div>
      <div class="col-sm mb-4">
        <label for="confirm_password" class="form-label font_color"
          >Confirmar Contraseña:</label
        >
        {{form.password2}}
      </div>
    </div>

    <div class="mb-3">
      <input
        type="checkbox"
        class="form-check-input was-validated"
        name="connected"
        required=""
      />
      <label for="connected" class="form-check-label"
        >Acepta nuestro terminos y condiciones</label
      >
    </div>

    <div class="d-grid gap-2">
      <button type="submit" class="btn1 btn-primary">Registrarse</button>
    </div>
    <div class="my-3">
      <p>
        ¿Ya tienes cuenta?
        <a class="texto" href="{% url 'SignIn' %}">Iniciar Sesión</a> <br />
      </p>
    </div>
  </form>
</div>

{% endblock form %}

CitasMecanica/usuario/templates/autenticacion/base.html
<!DOCTYPE html>
<html lang="es">

<head>
  <title>{% block title %}{% endblock title %}</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="shortcut icon" href="{% static 'core/img/login.png' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
  <link rel="stylesheet" href="{% static 'core/css/menu.css' %}">

<body>
  <div class="container w-75 mt-5 rounded-3 SignIn">
    <div class="row align-items-lg-stretch">
      <div class="col bg d-none d-lg-block col-responsive">
        <style>
          .bg {
            background: rgba(0, 0, 0, 0.90);
            border-top-left-radius: 0.375rem;
            border-bottom-left-radius: 0.375rem;
            background-image: url('{% static "core/img/Principal.png" %}');
            background-size: 85%;
            background-position: center center;
          }

          .asteriskField {
            display: none;
          }
        </style>
      </div>
      {% block form %}{% endblock form %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
    crossorigin="anonymous"></script>
</body>

</html>

CitasMecanica/usuario/templates/autenticacion/password-confirm.html
{% extends 'autenticacion/base.html' %}

{% block title %}Recuperar Contraseña{% endblock title %}

{% block form %}

<div class="col bg-white p-5 rounded-end">
    <h2 class="fw-bold text-center py-5">Nueva contraseña</h2>
    {% if form.errors %}
                {% for field in form %}
                {% if field.errors %}
                {% for error in field.errors %}
                <script>
                    $.alert({
                        title: '',
                        theme:'material',
                        type: 'red',
                        content: '{{ error | escape }}'
                    });
                </script>
                {% endfor %}
                {% endif %}
                {% endfor %}


                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <script>
                        $.alert({
                            title: '¡Importante!',
                            theme:'material',
                            type: 'red',
                            content: '{{ error | escape }}'
                        });
                </script>
                {% endfor %}
                {% endif %}
            {% endif %}
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="inlineFormInputGroupUsername" class="form-label fw-bolder">Contraseña:</label>
        <input class="form-control" type="password" name="{{form.new_password1.name}}" autocomplete="new-password" required="" id="id_new_password1">
    </div>
    <div class="mb-5">
        <label for="inlineFormInputGroupUsername" class="form-label fw-bolder">Confirmar Contraseña:</label>
        <input class="form-control" type="password" name="{{form.new_password2.name}}" autocomplete="new-password" required="" id="id_new_password2">
    </div>
    <div class="d-grid gap-2 mb-3">
        <button type="submit" class="btn1 btn-primary">Restablecer contraseña</button>
    </div>
</form>
</div>
{% endblock form %}

CitasMecanica/usuario/templates/autenticacion/password-reset.html
{% extends 'autenticacion/base.html' %} 
{% block title %}Recuperar Contraseña{% endblock title %} 

{% block form %}
<div class="col bg-white p-5 rounded-end">
  <h2 class="fw-bold text-justify py-5">Resetear contraseña</h2>
  <h5 class="fw-bold text-justify pb-4 pt-2">
    Ingresa su correo electrónico y le enviaremos instrucciones para ingresar
    una nueva contraseña
  </h5>
  {% if form.errors %}
                {% for field in form %}
                {% if field.errors %}
                {% for error in field.errors %}
                <script>
                    $.alert({
                        title: '',
                        theme:'material',
                        type: 'red',
                        content: '{{ error | escape }}'
                    });
                </script>
                {% endfor %}
                {% endif %}
                {% endfor %}


                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <script>
                        $.alert({
                            title: '¡Importante!',
                            theme:'material',
                            type: 'red',
                            content: '{{ error | escape }}'
                        });
                </script>
                {% endfor %}
                {% endif %}
            {% endif %}
  <form method="POST" class="pb-3">
    {% csrf_token %}
    <label for="inlineFormInputGroupUsername" class="form-label fw-bolder">Correo Electrónico:</label>
    <input class="form-control" type="email" name="{{form.email.name}}" autocomplete="email" maxlength="254" required="" id="id_email">
    <div class="d-grid gap-2">
    <button type="submit" class="btn1 btn-primary">Enviar Correo</button>
    <a class="btn btn-secondary" href="{% url 'SignIn' %}" role="button">Regresar</a>
</div>
  </form>
</div>
{% endblock form %}

CitasMecanica/usuario/templates/autenticacion/password_reset_complete.html
{% extends 'autenticacion/base.html' %} 
{% block title %}Recuperar Contraseña{% endblock title %} 

{% block form %}
<div class="col bg-white p-5 rounded-end">
    <div class="container p-5">
        <h2 class="font-weight-bold mt-3">Restablecimiento de contraseña completado</h2>
            <hr>
            <p>Su contraseña ha sido establecida. Ahora puede continuar e iniciar sesión.</p>
            <div class="d-grid gap-2 mt-3">
                <a class="btn btn-secondary btn1" href="{% url 'SignIn' %}" role="button">Iniciar Sesión</a>
            </div>
    </div>
</div>
{% endblock form %}

CitasMecanica/usuario/templates/autenticacion/password_reset_done.html
{% extends 'autenticacion/base.html' %} 
{% block title %}Recuperar Contraseña{% endblock title %} 

{% block form %}
<div class="col bg-white p-5 rounded-end">
    <div class="container p-5">
        <h2 class="font-weight-bold mt-3">Restablecimiento de contraseña enviado</h2>
            <hr>
            <p>Te hemos enviado un correo con un enlace para reestablecer tu contraseña</p>
    </div>
</div>
{% endblock form %}

CitasMecanica/usuario/templates/autenticacion/signIn.html
{% extends 'autenticacion/base.html' %}

{% block title %}Inicio de Sesión{% endblock title %}

{% block form %}
<div class="col bg-white p-5 rounded-end">
    <h2 class="fw-bold text-center py-5">Inicio de Sesión</h2>
    {% if form.errors %}
                {% for field in form %}
                {% if field.errors %}
                {% for error in field.errors %}
                <script>
                    $.alert({
                        title: '',
                        theme:'material',
                        type: 'red',
                        content: '{{ error | escape }}'
                    });
                </script>
                {% endfor %}
                {% endif %}
                {% endfor %}


                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <script>
                        $.alert({
                            title: '¡Importante!',
                            theme:'material',
                            type: '#fffff',
                            content: '{{ error | escape }}'
                        });
                </script>
                {% endfor %}
                {% endif %}
            {% endif %}
    <!--Login-->
    <form method="POST" class="mb-2">
        {% csrf_token %}

        <div class="mb-4">
            <label for="inlineFormInputGroupUsername" class="form-label">Nombre usuario</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label for="inputPassword4" class="form-label">Contraseña</label>
            {{ form.password }}
        </div>
        <div class="text-end mb-2">
            <p class="recup"><a class="txt" href="{% url 'password_reset' %}">¿Olvidó su contraseña?</a></p>
        </div>
        <div class="d-grid gap-2">
            <button type="submit" class="btn1 btn-primary">Iniciar Sesión</button>
        </div>
        <div class="my-3">
            <span>¿No tienes cuenta? <a class="texto" href="{% url 'SignUp' %}">Registrarse</a> <br></span>
        </div>
    </form>
</div>
{% endblock form %}